export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


export const REGISTER_REQUEST = "LOGIN_REQUEST";
export const REGISTER_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAIL = "LOGIN_FAIL";

export const GET_RESTAURANT_LIST_REQUEST ='GET_RESTAURANT_LIST_REQUEST';
export const GET_RESTAURANT_LIST_SUCCESS ='GET_RESTAURANT_LIST_SUCCESS';
export const GET_RESTAURANT_LIST_FAILED ='GET_RESTAURANT_LIST_FAILED';


export const GET_RESTAURANT_DATA_SUCCESS = 'GET_RESTAURANT_DATA_SUCCESS'
export const GET_RESTAURANT_DATA_FAILURE = 'GET_RESTAURANT_DATA_FAILURE'
export const SET_RESTAURANT = 'SET_RESTAURANT'
export const SET_RESTAURANT_ID = 'SET_RESTAURANT_ID'


export const RESERVATION_SUCCESS = 'RESERVATION_SUCCESS'


